In [32]:
import pandas as pd

In [33]:
df = pd.read_csv(r"C:\Users\USER\Desktop\PROject\spotify\DATA\clean_spotify_data.csv")

In [34]:
df

,artists,track_name,track_genre,danceability,energy,key,loudness,acousticness,instrumentalness,liveness,valence,tempo
0,10357,11741,0,0.629244,-0.717148,-1.210442,0.300828,-0.850202,-0.504109,0.758743,0.929306,-1.141863
1,3287,22528,0,-0.845908,-1.889980,-1.210442,-1.784744,1.831732,-0.504094,-0.591211,-0.798690,-1.489717
2,12397,60774,0,-0.742186,-1.122669,-1.491343,-0.293288,-0.315499,-0.504112,-0.507167,-1.365688,-1.528312
3,14839,9580,0,-1.733304,-2.312994,-1.491343,-2.039252,1.774593,-0.503883,-0.428376,-1.276974,1.987859
4,5255,25689,0,0.295030,-0.788711,-0.929541,-0.282750,0.463399,-0.504112,-0.686285,-1.184403,-0.073348
...,...,...,...,...,...,...,...,...,...,...,...,...
113995,22486,53329,113,-2.274962,-1.615656,-0.086838,-1.617326,0.977652,2.493755,-0.668426,-1.697787,0.128333
113996,22486,65090,113,-2.263437,-2.084789,-1.491343,-2.000082,2.042245,2.648817,-0.570200,-1.693545,-1.231195
113997,4952,38207,113,0.358416,-1.241940,-1.491343,-0.524135,1.660315,-0.504112,-0.681033,1.037306,0.341255
113998,18534,21507,113,0.116398,-0.538241,0.474964,-0.522942,0.198754,-0.504112,0.296502,-0.235548,0.460742
113999,4952,5999,113,-0.235103,-0.613780,-1.210442,-0.386740,1.100952,-0.504112,-0.652668,0.902306,-1.432709

In [35]:
df_sample = df.sample(n=5000, random_state=42)

In [36]:
x= df_sample.drop(['track_genre', 'artists','track_name'], axis= 1 )
y= df_sample['track_genre']

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=42)

In [39]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 50,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [40]:
model.score(x_test, y_test)

0.143

In [41]:
model.score(x_train, y_train)

0.97975

In [42]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [43]:
lr.score(x_test, y_test)

0.019663429031197

In [44]:
lr.score(x_train, y_train)

0.015812776659502092

In [45]:
pred= model.predict(x_test)

In [46]:
pred

array([ 96,  36,  78, 109,  29,  46,  60,  99,  68,  29,  16,  51,  69,
        47,  56,  67,  90,  84,   7, 113,   8,  28, 101,  96,   8,  73,
        73,  68,   6,  51,  79,  40,  36, 111,  67,  55,  12,   8, 106,
        42,   0, 105,   3,  44,  44,  79,  28,  40,  60,  84,  27,  71,
        34,  92,   1,  99,  86,  29,  97,  70,  47,  65,  18,  10,  65,
        53,  75,  45,  75,  60,  53,  33, 109,  30,  36,  36,   5,  12,
        21,  73,  73,  49,  58,  77,  41,  81,  12,  73,  78,  14,  14,
        64,  54,   2,  16,  24,  81,  70,  21, 105,  77,  64,  55,  81,
        16,  28,  25,  63,  92,  35,  16,  12,  98,   1,  11, 104,  56,
       108, 105,  71,  92,  39,  12,   6,  42,  33,  61,  50,  92, 101,
       108,  96,  64,  93,  70,  71,  68,   2,  82,  13,   3,  96,  16,
        50,  17,  43,  50,  78,  96,  36,  45,  84,  23, 104,  12,   1,
        32,  92,   4,  44, 110,  24, 111,  64,  90,  48, 108,  73,  69,
         0,  53,  48,  40,  23,  15,  67,  64,  51,  14,  29,  51,  40,
        12,  10,  46,  64,  98, 109,  91,  29,   6,  34,  14,  49,  45,
         0,  46,  77,  96,  92,  61,  25,  11,  47,  93,  31,  50,  60,
        16,  81,  23,  62,  70,  64,  35,  60,  18,  73,  58,  50,  95,
       102,  62,  42, 102,  52, 113,  46,  88,  11,  22,  92,  67,  26,
        12,  38,  78,  78,  49,  11,  29,  70,  72,  78,  10, 105,  48,
        78,  19,  43,  88, 111,   8,  61,  20,  61,  49,  21,  87,  99,
        73,  30,  34,  35,   0,  77,   7,  44,  88,  17,  54,  50,   2,
        98,  13,  10,  60,  42,  64,  53,  66,  57,  25,  16,   0,  31,
        98,  54,  97,  93,   2,   1,   6,  61,   9,  91,  30,  86,  29,
       107,  10,  49,  99,  31,  42, 107, 106,  58,  40,   4,  31,  96,
        99,  25,  30, 105,  19,  88,  97,  80,  53,  17,  96,  46,  64,
       105,   4,  14,  70, 104,  77,  52,  88, 101,  42,   9,   7,  84,
        31,  70, 108, 110,  72,  58, 108,  44, 109,  80,  31,  71,  15,
         3,  15,  21,  65,  60,   6,  67,  50,  15,  19, 105,  92,  55,
        73,  94,  60,  71,  78,   6,   7,  95,  59,  75,  17,  71,  23,
        40, 104,  16, 105,  29, 101,   6,  73,   8,  65,  46,  54, 113,
        30,  95,  39,   0,  85,  44,  92,  10, 103,  96,  31,  44,  43,
       100,  10,  76,  78,  40,  86,  20,  60,  42,  98,  58,  78,  16,
        69,  97, 103,  96,  22,  67,  15,  79,  64, 105, 110,  96,  42,
        20,  70,  54,  55,   1, 109,   2,  75,  44,   1,  84,  16,  53,
        65,  68,   7,  82,  79,  30,  55,  30,  20,   9,  99,   5,  52,
        38,   0, 113,   4, 108,   0,  48,  40,  84,  51,  29,  70,  49,
        60,  71,   7,  75, 100,  12,  83,  96, 108,  16,  60,  16,  55,
        78,  35,  80,  92,  54, 108,   0,  67,   8,  81,  53,  14,  14,
        11,  25,  97,  40,  12,  58,   6, 101,  68,  31,  70,   8, 107,
        81,  88,  98,  72,  76,  11,  27, 108,  82,  83,  12,  64,  51,
        61,  83,   5,  47,  94,  11,  23,  68,   6,  10,  64,  70,  87,
        70,  54,  31, 106,   0,   0,  12, 110,  53,  53,  25, 105,   2,
        53,  23,  45,  31,   1,  20, 113,  21,  76,  92,   2,  78,  40,
        75,  61,  36, 109,  83,  18,  21,  31, 112,  29,  10,  93,  17,
        93,  53,  87, 110,  76,  38,  54,  26,  40,   1,  58,  52,  71,
        93,  98,  49,  17,  59,  22,  14,  86,   4,  20,  40,  52, 108,
        59, 108,  64,  34,   0,  57,  80,   2,  60,   6,   2,  61,  33,
        70,  82,  51,  36,   2,  59, 111,  49,  37,  30,  57,  11,  93,
        93,  60,  41,  60,  19,  98, 106,  38,  90, 101,  73,  81,  43,
        91, 105,  81,  49, 108, 105,  93,  51,  84,   6,  36,  10,  15,
        79,  66,  58, 105,  42,  63,  36,  85,  70,  52,  78,  99,  58,
         6,  11,  10,  12,  81,  80,  66,  93,  84,  96,  53,  45,  91,
        77,  96,  25,  67,   4,  19,   4,  23,   4,  49,  15,  51, 108,
        29,  36,  69,  29,  87,  70,   9,  14,   9,   0,   8,  29,  25,
        21,  70, 101,  64,   9,  42,  34,  70, 110,  93,  46,   4,  70,
         9, 105,  42,  34,  40,  60,  94,  96, 108,  10,  90,  83,  13,
        64,  12, 108,  55,  56,  55,  64,   2,  23,  26, 106,  64, 100,
        37,  17,  18, 110,  95,   5,  80,  30,  19,  19,  96,  11,  88,
         6,  19,  80,  48,  26, 110,  45,  39,  19,  31,  10,   0,  36,
        60, 107,   8,  49,  49,  35,  34,  77,  14,  67,  81,  49,   1,
        68, 108,   6,  22,  93,  34,   2,  84,  75,   6,  42,  61,  97,
        62,  14,  61,  12,   9,  95,  80,  82,  40,  66,  58,  42,   7,
        16,  44,  31,  75,  79,  62,  75,  29,   5,  68,  64,  94, 108,
        30,  37,  70,  50,   8,  12,  49,  78,  29,  69,  31, 112,  81,
        76,  35, 105,  83,  18,  17,  66,  48,   9,  15,   6,  53,  16,
        76,  52,  93,   1,  59,  70,  21, 105,  54,  68,  54,  31,   2,
        77, 102,  77,  60,  14,  29,  71,   7,  86,  94, 106,  50,  46,
        13,  42,  10,  92,  26, 113,  28, 111,  40,  30, 112,  62,  13,
       108,  50,  51,  13,  82,  31,  55,  73,  72,  55,  96,  31,  30,
         6, 105,  43,  89,  53,   5,  85,  64,  60,  73,  21,  19,  19,
        58,  73,  12,  64,  18,  61,  48, 101,  36,  58,  21,   1,  30,
        67,  14,  23,  37, 113,  77,  13,  23,  19,   4,  11,  68,  57,
        50,  43,  78,  20,  99,  23, 106,  25, 108, 107,  24,  21,  18,
        62,  82,  38,   1,  40,  47,  76,  74,  86,  86,  90,  75,  99,
        76,  23,  53,  96,  11,   1,   4,   6,  50,   9,  29, 102,  53,
       109,  28,  15,  36,  56, 103,   3, 107,  46,  67,  95,  44,  65,
         7,   2,   1,   7,  57,  15,  54,  94,  52,  49,  37,  78])

In [47]:
pred= pd.DataFrame(pred)

In [48]:
pred

       0
0     96
1     36
2     78
3    109
4     29
..   ...
995   94
996   52
997   49
998   37
999   78

[1000 rows x 1 columns]

In [49]:
y_test

87149    87
94536    94
55285    55
13821    13
33804    33
         ..
74063    74
38757    38
46148    46
51683    51
58050    58
Name: track_genre, Length: 1000, dtype: int64

In [50]:
pd.concat([pred, y_test], axis=1)

           0  track_genre
0       96.0          NaN
1       36.0          NaN
2       78.0          NaN
3      109.0          NaN
4       29.0          NaN
...      ...          ...
74063    NaN         74.0
38757    NaN         38.0
46148    NaN         46.0
51683    NaN         51.0
58050    NaN         58.0

[1994 rows x 2 columns]

In [51]:
import joblib
joblib.dump(model, 'model.lb')

['model.lb']